### ISSUE TITLE
What does TF stands for in Accuracy equation?

### ISSUE THREAD

**Issue by Sargaleano** [blmoistawinde/ml_equations_latex#2]
Hi, and thank you for this useful resource.

I was checking the definition of Accuracy in the Classification Metrics section. There you wrote:

Accuracy = \frac{TP+TF}{TP+TF+FP+FN}

I believe TF is not an actual quantity, and maybe you meant to refer to TN (true negative) in this equation.

Cheers,
-- SergioA.

**Comment by blmoistawinde** [comment]
Thank you for pointing this out, this should be a typo. Already fixed now.
