### ISSUE TITLE
small mistake with minimax loss for GANs

### ISSUE THREAD

**Issue by 1hachem** [blmoistawinde/ml_equations_latex#3]
you describe the second term in the loss function as being 
![73a74fecdf905de90d65ea9f76d8f903](https://user-images.githubusercontent.com/84399880/158808171-cd9a9c66-01a4-4a20-8131-24f912ad6dab.png)
however z is sampled from a random distribution and not from the generated one, instead it should be :
![78f6d4ee29227837055faa6b02d72835](https://user-images.githubusercontent.com/84399880/158808369-a8f725b7-c6fb-4bb8-8cae-ca08e20a4b7a.png)
kind regards to check this out, and thank you for the amazing work !

**Comment by blmoistawinde** [comment]
Thanks for pointing this out, already fixed now
