### ISSUE TITLE
Mistake in the generator loss of GAN

### ISSUE THREAD

**Issue by m-gangloff** [blmoistawinde/ml_equations_latex#4]
Thank you very much for your work. For the generator part, the ```1 -``` should be inside the log, s.t. if the generator fools the discriminator s.t.  ```D(G(x)) = 0``` then ```log(1 - D(G(x)) = 0```. Right now you have ```1 - log(D(G(x))``` instead which is not defined for ```D(G(x)) = 0```.

The correct formula should be such as described in the [paper](https://arxiv.org/abs/1406.2661):
```
\min_{G}\max_{D}V(D, G) = \mathbb{E}_{x\sim p_{\text{data}}(x)}[\log{D(x)}] +  \mathbb{E}_{z\sim p_{\text{z}}(z)}[\log{(1-D(G(z)))}]
```

```math
\min_{G}\max_{D}V(D, G) = \mathbb{E}_{x\sim p_{\text{data}}(x)}[\log{D(x)}] +  \mathbb{E}_{z\sim p_{\text{z}}(z)}[\log{(1-D(G(z)))}]
```

instead of:
```
\min_{G}\max_{D}\mathbb{E}_{x\sim p_{\text{data}}(x)}[\log{D(x)}] +  \mathbb{E}_{z\sim p_{\text{z}}(z)}[1 - \log{D(G(z))}]
```

```math
\min_{G}\max_{D}\mathbb{E}_{x\sim p_{\text{data}}(x)}[\log{D(x)}] +  \mathbb{E}_{z\sim p_{\text{z}}(z)}[1 - \log{D(G(z))}]
```

**Comment by blmoistawinde** [comment]
Thank you for pointing this out! Already fixed.
